AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy The Lotlytics API Lambda function with API Gateway using AWS SAM

Globals:
  Function:
    MemorySize: 2048
    Runtime: java21
    Architectures:
      - x86_64
    AutoPublishAlias: prod
    SnapStart:
      ApplyOn: PublishedVersions

Resources:
  LotlyticsApiOnLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lotlytics-api-lambda
      CodeUri: .
      Handler: com.lotlytics.api.LambdaHandler::handleRequest
      Description: The Lotlytics RESTful API Lambda function running on Spring Boot 3
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: lotlytics-api
      StageName: prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref LotlyticsApiOnLambda
  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt LotlyticsApiOnLambda.Arn
